export { default as contactsList } from './contactsList'
export { default as detailContact } from './contactDetail'
export { default as authModule } from './auth'
export { default as editContact } from './editContact'
export { default as addContact } from './addContact'